routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LeaveController;
use App\Http\Controllers\ReferenceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware('auth')->group(function () {
    Route::get('/senarai-cuti', [LeaveController::class,'SenaraiCuti']);
    Route::get('/borang-cuti/{id?}', [LeaveController::class,'MohonCuti'])->name('borang.cuti');//create&edit
    Route::post('/simpan-cuti/{id?}', [LeaveController::class,'SimpanCuti'])->name('simpan.cuti');//store&update


    Route::get('/cipta-cuti', [LeaveController::class,'BorangCuti'])->name('mohon.cuti');//create
    Route::post('/cipta-cuti', [LeaveController::class,'CiptaCuti'])->name('cipta.cuti');//store
    Route::get('/kemaskini-cuti/{id}', [LeaveController::class,'UbahCuti'])->name('ubah.cuti');//edit
    Route::post('/kemaskini-cuti/{id}', [LeaveController::class,'KemaskiniCuti'])->name('kemaskini.cuti');//update

    Route::post('/batal-cuti', [LeaveController::class,'BatalCuti']);
    Route::post('/status-cuti/{jenis_cuti}/{status?}', [LeaveController::class,'StatusCuti']);
    Route::delete('/hapus-cuti/{id}', [LeaveController::class,'HapusCuti']);
    
    // Route::resource('references', ReferenceController::class);

    Route::prefix('reference')->group(function () {
        
            Route::get('/index', [ReferenceController::class,'index'])->name('reference.index');
            Route::get('/create', [ReferenceController::class,'create'])->name('reference.create');
            Route::post('/store', [ReferenceController::class,'store'])->name('reference.store');
            Route::get('/edit/{id}', [ReferenceController::class,'edit'])->name('reference.edit');
            Route::patch('/update/{id}', [ReferenceController::class,'update'])->name('reference.update');
            Route::delete('/destroy/{id}', [ReferenceController::class,'destroy'])->name('reference.destroy');
        
    });
    
    // Route::get('/reference/index', [ReferenceController::class,'index'])->name('reference.index');
    // Route::get('/reference/create', [ReferenceController::class,'create'])->name('reference.create');
    // Route::post('/reference/store', [ReferenceController::class,'store'])->name('reference.store');
    // Route::get('/reference/edit/{id}', [ReferenceController::class,'edit'])->name('reference.edit');
    // Route::patch('/reference/update/{id}', [ReferenceController::class,'update'])->name('reference.update');
    // Route::delete('/reference/destroy/{id}', [ReferenceController::class,'destroy'])->name('reference.destroy');


    Route::resource('pengguna', UserController::class);


});





require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use Illuminate\Validation\Rules;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();

        // if(Storage::disk('public')->exists('avatars/'.Auth::user()->id.'.jfif'))
        // $url = Storage::url('avatars/'.Auth::user()->id.'.jfif');
        // else
        $avatar = Storage::url('avatars/default.jfif');

        return view('user._form',compact('user','avatar'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $req)
    {
        // dd($req);
        $req->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:'.User::class],
            'katalaluan' => ['required', 'confirmed', Rules\Password::defaults()],
        ]);

        $user = new User();
        $user->name = $req->name;
        $user->email = $req->email;
        $user->password = Hash::make($req->katalaluan);
        $user->save();

        $file = $req->file('attachment');
        if (isset($file)){
            $extension = $file->getClientOriginalExtension();
            $rename = $user->id.'.'.$extension;        
            $req->file('attachment')->storeAs('public/avatars', $rename);
        }
        

        return redirect(route('pengguna.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        if(Storage::disk('public')->exists('avatars/'.$user->id.'.jfif'))
        $avatar = Storage::url('avatars/'.$user->id.'.jfif');
        else
        $avatar = Storage::url('avatars/default.jfif');

        return view('user._form',compact('user','avatar'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        $req->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'katalaluan' => ['required', 'confirmed', Rules\Password::defaults()],
        ]);

        $user = User::find($id);
        $user->name = $req->name;
        $user->email = $req->email;
        $user->password = Hash::make($req->katalaluan);
        $user->save();

        $file = $req->file('attachment');
        // dd($file);
        if (isset($file)){
            // dd($file);
            $extension = $file->getClientOriginalExtension();
            $rename = $user->id.'.'.$extension;        
            $req->file('attachment')->storeAs('public/avatars', $rename);
        }
        

        return redirect(route('pengguna.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id)->delete();
        return redirect(route('pengguna.index'));
    }
}

resources/views/user/_form.blade.php
@extends('layouts.zeta_login')
@section('title', 'Borang Pengguna')
@section('content')
    <h1>Borang Pengguna</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(!empty($user->id))
    <form action="{{route('pengguna.update',$user->id)}}" method='POST' enctype="multipart/form-data">
        @method('PATCH')
    @else
    <!-- <form action="{{route('pengguna.store')}}" method='POST' enctype="multipart/form-data"> -->
    <form action="/user" method='POST' enctype="multipart/form-data">
    @endif
        @csrf
        <img src="{{$avatar}}" alt="avatar" 
    class="rounded-circle" height="48" width="48">
        <div class="col-sm-4">
            <div class="mb-3">
                <label for="name" class="form-label">Nama<span class="mandatory">*</span></label>
                <input type="text" name="name" id="name" value="{{old('name', $user)}}" class="form-control">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email<span class="mandatory">*</span></label>
                <input type="text" name="email" id="email" value="{{old('email', $user)}}" class="form-control">
            </div>
            <div class="mb-3">
                <label for="end_dt" class="form-label">Katalaluan<span class="mandatory">*</span></label>
                <input type="password" name="katalaluan" id="katalaluan" value="{{old('password', $user)}}" class="form-control">
            </div>
            <div class="mb-3">
                <label for="confirmed" class="form-label">Pengesahan Katalaluan<span class="mandatory">*</span></label>
                <input type="password" name="katalaluan_confirmation" id="katalaluan_confirmation" value="{{old('password', $user)}}" class="form-control">
            </div>

            <div class="mb-3">
                <label for="attachment" class="form-label">Gambar Profil<span class="mandatory">*</span></label>
                <input type="file" name="attachment" id="attachment" class="form-control">
            </div>
            <div class="mb-3">
                <input type="submit" value="{{empty($user->id)?'Simpan':'Kemaskini'}}" class='btn btn-primary'>
                @if(!empty($user->id))
                <a href="{{route('pengguna.edit',$user->id)}}" class='btn btn-secondary'>Set Semula</a>
                @else
                <a href="{{route('pengguna.create')}}" class='btn btn-secondary'>Set Semula</a>
                @endif
                <a href="{{route('pengguna.index')}}" class='btn btn-danger'>Kembali</a>
            </div>
        </div>

    </form>
    @endsection

resources/views/user/index.blade.php
@extends('layouts.zeta_login')
@section('title', 'Senarai Pengguna')
@section('content')
<h2>Senarai Pengguna</h2>
<a href="{{route('pengguna.create')}}" class='btn btn-primary'>Tambah Pengguna</a>
<table class="table table-striped">
    <tr>
        <th>Bil</th>
        <th>Nama</th>
        <th>Tindakan</th>
    </tr>

@php 
$i = 1;
@endphp
@foreach($users as $m)
<tr>
    <td>{{$i++}}</td>
    <td>{{$m->name}}</td>
    <td>
    <form id="delete_{{$m->id}}" action="{{route('pengguna.destroy',$m->id)}}" method='POST'>
        @csrf
        @method('DELETE')
        <a href="{{route('pengguna.edit',$m->id)}}" class='btn btn-secondary'>Kemaskini</a>
        <a href="#" class='btn btn-danger' onclick="deleteRecord({{$m->id}})">Hapus</a>
    </form>
    </td>
</tr>
@endforeach
</table>
@endsection